create table specie (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

INSERT INTO specie (id, name) VALUES
    (1L, 'Dog'),
    (2L, 'Cat');