-- INSERT INTO batch (code, genetic_material_id, staking_date, amount, sapling_selection_id) VALUES
--     ("321/2023", 1, "2023-09-19", 1000),
--     ('AEC 144', 1),
--     ('K2000', 1),
--     ('K2001', 1),
--     ('2864', 2),
--     ('GG 157', 1),
--     ('WRK 8801', 3),
--     ('KF 114', 4),
--     ('KF 101', 4),
--     ('WRK 4707', 3),
--     ('IPB 01', 1);



--     create table batch (
--         id bigint generated by default as identity,
--         code varchar(255) not null unique,
--         genetic_material_id bigint not null,
--         staking_date date not null,
--         amount integer not null,
--         sapling_selection_id bigint,
--         primary key (id)
--     );