    create table batch (
        amount integer not null,
        id integer generated by default as identity,
        specie_id integer unique,
        staking_date date not null,
        code varchar(255) not null,
        primary key (id)
    );

    create table genetic_material (
        id integer generated by default as identity,
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table sapling_selection_has_batch (
        batch_id integer not null,
        sapling_selection_id integer not null
    );

    create table sapling_selection (
        id integer generated by default as identity,
        selection_date date not null,
        total_rooted_seedlings integer not null,
        primary key (id)
    );

    create table specie (
        genetic_material_id integer unique,
        id integer generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists batch 
       add constraint FKtdp72qt11ouf8fsw5jeel7qau 
       foreign key (specie_id) 
       references specie;

    alter table if exists sapling_selection_has_batch 
       add constraint FKc4fg9wxlkcsdqyun3m0prl54g 
       foreign key (batch_id) 
       references batch;

    alter table if exists sapling_selection_has_batch 
       add constraint FKhr360rbw5bcpvaj4phtmcf49f 
       foreign key (sapling_selection_id) 
       references sapling_selection;

    alter table if exists specie 
       add constraint FKqnybrurlao4c8mubxeymh9qyk 
       foreign key (genetic_material_id) 
       references genetic_material;
