
    create table batch (
        amount integer not null,
        id integer generated by default as identity,
        sapling_selection_id integer,
        staking_date date not null,
        genetic_material_id bigint not null,
        code varchar(255) not null,
        primary key (id)
    );

    create table client (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table expedition_plan (
        month smallint not null check (month between 0 and 11),
        planned integer not null,
        realized integer,
        client_id bigint not null,
        genetic_material_id bigint not null,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table genetic_material (
        id bigint generated by default as identity,
        specie_id bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table sapling_selection (
        id integer generated by default as identity,
        selection_date date not null,
        total_rooted_seedlings integer not null,
        primary key (id)
    );

    create table specie (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists batch 
       add constraint FK37mjv5ef6o23vfe41p2heh1j0 
       foreign key (genetic_material_id) 
       references genetic_material;

    alter table if exists batch 
       add constraint FKq53lgtawjd8ugnscyyk562jev 
       foreign key (sapling_selection_id) 
       references sapling_selection;

    alter table if exists expedition_plan 
       add constraint FKr4ibe9nbs0neulxy22113d02b 
       foreign key (client_id) 
       references client;

    alter table if exists expedition_plan 
       add constraint FK2u2b40foyjcic035ysuc77pyp 
       foreign key (genetic_material_id) 
       references genetic_material;

    alter table if exists genetic_material 
       add constraint FKpcteip4kwtsm27b8feordmlag 
       foreign key (specie_id) 
       references specie;
