
    create table batch (
        amount integer not null,
        id integer generated by default as identity,
        staking_date date not null,
        genetic_material_id bigint unique,
        code varchar(255) not null,
        primary key (id)
    );

    create table client (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table expedition_plan (
        month int not null check (month between 0 and 11),
        planned integer not null,
        realized integer,
        genetic_material_id bigint unique,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table genetic_material (
        id bigint generated by default as identity,
        specie_id bigint unique,
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table sapling_selection_has_batch (
        batch_id integer not null,
        sapling_selection_id integer not null
    );

    create table sapling_selection (
        id integer generated by default as identity,
        selection_date date not null,
        total_rooted_seedlings integer not null,
        primary key (id)
    );

    create table specie (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists batch 
       add constraint FK37mjv5ef6o23vfe41p2heh1j0 
       foreign key (genetic_material_id) 
       references genetic_material;

    alter table if exists expedition_plan 
       add constraint FK2u2b40foyjcic035ysuc77pyp 
       foreign key (genetic_material_id) 
       references genetic_material;

    alter table if exists genetic_material 
       add constraint FKpcteip4kwtsm27b8feordmlag 
       foreign key (specie_id) 
       references specie;

    alter table if exists sapling_selection_has_batch 
       add constraint FKc4fg9wxlkcsdqyun3m0prl54g 
       foreign key (batch_id) 
       references batch;

    alter table if exists sapling_selection_has_batch 
       add constraint FKhr360rbw5bcpvaj4phtmcf49f 
       foreign key (sapling_selection_id) 
       references sapling_selection;
